app without sub does a simple mapping into script

diff --git a/bin/app b/bin/app
--- a/bin/app
+++ b/bin/app
@@ -1,19 +1,17 @@
 #!/usr/bin/env bash
 
 function main {
-  case "${1:-}" in
-    bootstrap)
-      local shome="$(unset CDPATH; cd -P -- "$(dirname -- "$BASH_SOURCE")/.." && pwd -P)"
-      "$shome/script/bootstrap"
-      ;;
-    "")
-      true
-      ;;
-    *)
-      echo "ERROR: command $1 unimplemented" 1>&2
-      return 1
-      ;;
-  esac
+  if [[ "$#" = "0" ]]; then
+    return 0
+  fi
+
+  if [[ -x "$shome/script/$1" ]]; then
+    local shome="$(unset CDPATH; cd -P -- "$(dirname -- "$BASH_SOURCE")/.." && pwd -P)"
+    "$shome/script/$1" "$@"
+  else 
+    echo "ERROR: command $1 unimplemented" 1>&2
+    return 1
+  fi
 }
 
 if [[ -x "$(which sub 2>&- || true)" ]]; then
