refactor actions in terms of list

diff --git a/exec/app-clone b/exec/app-clone
--- a/exec/app-clone
+++ b/exec/app-clone
@@ -1,13 +1,40 @@
 #!/usr/bin/env bash
 
+#!/usr/bin/env bash
+
 function main {
   local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
-
   source "$shome/script/profile" || return 1
 
-  source app_clone
+  local tmp_list="$(mktemp -t XXXXXX)"
+  block list > "$tmp_list"
+  while read -r nm_block pth_block id_block; do
+    local a="_clone_${nm_block//-/_}"
 
-  block_walker clone:need_clone "$@"
+    if [[ ! -d "$pth_block" ]]; then
+      local url_git="$(app map "$nm_block")"
+      if [[ -n "$url_git" ]]; then
+        git clone "$url_git" "$APP_PATH/$nm_block"
+        pth_block="$APP_PATH/$nm_block"
+        unset "$a"
+      else
+        echo "ERROR: could not find git repo for $nm_block" 1>&2
+        break
+      fi
+    fi
+
+    if [[ "$id_block" != "." ]]; then
+      if [[ "${!a:-}" != "$pth_block" ]]; then
+        read -r "$a" <<< "$pth_block"
+        export "$a"
+
+        pushd "$pth_block"
+        block clone
+        popd
+      fi
+    fi
+  done < "$tmp_list"
+  rm -f "$tmp_list"
 }
 
 source sub "$0" "$@"
diff --git a/exec/app_require b/exec/app_require
--- a/exec/app_require
+++ b/exec/app_require
@@ -1,42 +1,14 @@
 #!/usr/bin/env bash
 
-function mark_source {
-  local pth_profile="$1"; shift
-  debug echo INFO "$pth_profile" 1>&2
-}
-
 function source_pre {
   local pth_profiled
   set +f
   for pth_profiled in .profile.d/*.pre; do
     set -f
     if [[ -f "$pth_profiled" ]]; then
-      mark_source "$PWD/$pth_profiled"
       source "$pth_profiled"
     fi
   done
-}
-
-function source_profile {
-  local nm_block="${PWD##*/}"
-  if [[ -f .app-name ]]; then
-    read nm_block < .app-name
-  fi
-
-  local a="_require_${nm_block//-/_}"
-  if [[ -r "script/profile" ]]; then
-    if [[ -z "${!a:-}" ]]; then
-      mark_source "$PWD/script/profile"
-      eval "$a=1"
-      source "script/profile"
-    fi
-  else
-    echo "WARNING: script/profile not found in $PWD" 1>&2
-  fi
-
-  if [[ -r "script/rc" ]]; then
-    source "script/rc"
-  fi
 }
 
 function source_post {
@@ -45,23 +17,37 @@ function source_post {
   for pth_profiled in .profile.d/*.post; do
     set -f
     if [[ -f "$pth_profiled" ]]; then
-      mark_source "$PWD/$pth_profiled"
       source "$pth_profiled"
     fi
   done
 }
 
-function require_in {
-  local nm_project="$1"; shift
-
-  pushd "$nm_project" >/dev/null
-  source_pre || fl_error=1
-  into_blockfile require
-  source_profile || fl_error=1
-  source_post || fl_error=1
-  popd >/dev/null
-}
-
 function require {
-  block_walker "$FUNCNAME" "$@"
+  local tmp_profile="$(mktemp -t XXXXXX)"
+
+  local tmp_list="$(mktemp -t XXXXXX)"
+  block list > "$tmp_list"
+
+  while read -r nm_block pth_block id_block; do
+    if [[ ! -d "$pth_block" ]]; then
+      echo "ERROR: missing $nm_block block" 1>&2
+      set --
+      break
+    fi
+
+    source_pre
+    if [[ -e "$pth_block/script/profile" ]]; then
+      echo "source $pth_block/script/profile"
+    fi
+    if [[ -e "$pth_block/script/rc" ]]; then
+      echo "source $pth_block/script/rc"
+    fi
+    source_post
+
+  done < "$tmp_list" > "$tmp_profile"
+  rm -f "$tmp_list"
+
+  source "$tmp_profile"
+  rm -f "$tmp_profile"
 }
+
