get rid of script/rc

diff --git a/script/profile b/script/profile
--- a/script/profile
+++ b/script/profile
@@ -1,9 +1,56 @@
 #!/usr/bin/env bash
 
+# The `rc` profile provides the `require` function to source a block's
+# dependencies and profile.
+
+# ## Require
+function require {
+  # Ensure no arguments are passed to require.  Any arguments are passed on to
+  # profiles that are sourced without arguments.
+  set --
+
+  local tmp_list="$(mktemp -t XXXXXX)"
+  # Get a list of block dependencies.
+  block list > "$tmp_list"
+
+  # Generate a profile script to source block dependencies, for efficiency.
+
+  local tmp_profile="$(mktemp -t XXXXXX)"
+  # ### For each block dependency:
+  while read -r nm_block pth_block git_block end_block; do
+    # If a block is missing, break.  Something didn't bootstrap correctly or yet.
+    if [[ ! -d "$pth_block" ]]; then
+      echo "WARNING: missing $nm_block block" 1>&2
+      break
+    fi
+
+    # To avoid recalculating the block home, set it as `_$block_home`, replacing `.-\`
+    # with `_`
+    local nm_block_safe="${nm_block//-/_}"
+    nm_block_safe="${nm_block_safe//\//_}"
+    nm_block_safe="${nm_block_safe//\./_}"
+    local nm_pth_block="pth_block"
+    export "_${nm_block_safe}_home"="${!nm_pth_block}"
+
+    # If block profile is found, source it; assume profile will source rc as
+    # needed.  If only rc is found, source it.
+    if [[ -e "$pth_block/script/profile" ]]; then
+      echo "source $pth_block/script/profile"
+    fi
+
+  done < "$tmp_list" > "$tmp_profile"
+
+  # ### Finished with block deps
+  rm -f "$tmp_list"
+
+  # Actually source the dependencies by sourcing everything.
+  source "$tmp_profile"
+  rm -f "$tmp_profile"
+}
+
 function _block_profile {
   local shome="${_block_home:-"$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"}"
   PATH="$shome/bin:$shome/exec:$PATH"
-  source "$shome/script/rc"
 
   if [[ -z "${BLOCK_PATH:-}" ]]; then
     export BLOCK_PATH="$(cd -P -- "${BASH_SOURCE%/*}/../.." && pwd -P)"
