named args to require specify sub or peer projects

diff --git a/script/profile b/script/profile
--- a/script/profile
+++ b/script/profile
@@ -16,12 +16,39 @@ function profile {
   fi
 }
 
-function require {
+function source_profile {
   if [[ -r "script/"profile ]]; then
     source "script/profile"
   else
-    echo "ERROR: script/profile not found" 2>&2
+    echo "ERROR: script/profile not found in $(pwd)" 1>&1
+    return 0
   fi
+}
+
+function require {
+  local fl_error=0
+  # requiring specific projects?
+  if [[ "$#" -gt 0 ]]; then
+    local nm_project
+    for nm_project in "$@"; do
+      if [[ -d "$nm_project" ]]; then
+        pushd "$nm_project" 1>&-
+      elif [[ -d "../$nm_project" ]]; then
+        pushd "../$nm_project" 1>&-
+      else
+        echo "ERROR: could not find project $nm_project" 1>&2
+        fl_error=1
+        continue
+      fi
+
+      source_profile || fl_error=1
+      popd 1>&-
+    done
+  else
+    source_profile || fl_error=1
+  fi
+
+  return $fl_error
 }
 
 profile
